site_name: Klima-Check-Karten

site_description: Dokumentation der Datengrundlagen und Methoden
site_author: Juliane El Zobi
theme:
  name: material
  palette:
    primary: grey
  logo: gerics.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest

extra_css:
  - stylesheets/extra.css

nav:
- Einleitung: index.md
- Beobachtetes Klima:
  - Überblick: beobachtetes-klima/index.md
  - E-OBS Datensatz: beobachtetes-klima/eobs.md
- Zukünftiges Klima:
  - Überblick: zukuenftiges-klima/index.md
  - EURO-CORDEX Datensatz: zukuenftiges-klima/euro-cordex.md
  - Hintergrund zur Klimamodellierung: zukuenftiges-klima/hintergrund.md
  - Erläuterungen zu Klimaprojektionen: zukuenftiges-klima/Klimaszenarien.md 
  - Erläuterungen zu Robustheit: zukuenftiges-klima/robustheit.md
- Klimagrößen:
  - Überblick: klimagroessen/Allgemein.md
  - Definition der Klimagrößen: klimagroessen/Klimaindikatoren.md
  - Methode der Flächenmittelung: klimagroessen/Flaechenmittelung.md
  - Datengrundlage: klimagroessen/Modelle.md
- Mitwirkende: mitwirkende.md
- Impressum: impressum.md